version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=true
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - translation-network

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - LIVEKIT_WORKER_PORT=8080
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - translation-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge
